### ISSUE TITLE
Add basic python3 support.

### ISSUE THREAD

**Issue by kotbegemot** [blizgard/RocketJoe#30]
./rocketjoed init.py

    init  app 
```
https://github.com/smart-cloud/RocketJoe/blob/master/apps/rocketjoed/init_service.cpp
``` 
    init thread 
```
https://github.com/smart-cloud/RocketJoe/blob/master/services/lua_engine/lua_sandbox.cpp#L51
```
    run init.py in embedded python in thread

**Comment by leinlawun** [comment]
./rocketjoed init.py   
1) app
2) init thread 
3) run init.py in embedded python in thread
